# Generated by Django 4.1.4 on 2023-02-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_public',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Public Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='materials',
            field=models.ManyToManyField(blank=True, help_text='hold ctrl or cmd to select more than one', related_name='profile', to='users.material'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='hold ctrl or cmd to select more than one', related_name='profile', to='users.skill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_work',
            field=models.ManyToManyField(blank=True, help_text='hold ctrl or cmd to select more than one', related_name='profile', to='users.worktype'),
        ),
    ]
