# Generated by Django 4.1.4 on 2023-01-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_public',
            field=models.EmailField(blank=True, help_text='This email address will be displayed on your public SKID profile.', max_length=100, null=True, verbose_name='Public Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.material'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.skill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_work',
            field=models.ManyToManyField(blank=True, help_text='eg: Prototype, Production, Made to Order, etc.', related_name='profiles', to='users.worktype'),
        ),
    ]
