# Generated by Django 4.1.4 on 2022-12-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150)),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='state or province')),
                ('country', models.CharField(blank=True, max_length=56)),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='zip or postal code')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('business_name', models.CharField(blank=True, default='', max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('work_type', models.CharField(choices=[('none', 'None'), ('prototype', 'Prototype'), ('made to order', 'Made To Order'), ('small scale production', 'Small Scale Production'), ('large scale production', 'Large Scale Production'), ('consulting', 'Consulting')], default='none', help_text='Type of work you are able to provide.', max_length=50)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='directory.location')),
                ('materials', models.ManyToManyField(blank=True, to='directory.material')),
                ('skills', models.ManyToManyField(blank=True, to='directory.skills')),
            ],
        ),
    ]
