# Generated by Django 4.1.4 on 2022-12-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_remove_user_location_remove_user_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('none', 'None'), ('prototype', 'Prototype'), ('made to order', 'Made To Order'), ('small scale production', 'Small Scale Production'), ('large scale production', 'Large Scale Production'), ('consulting', 'Consulting')], default='none', help_text='Type of work you are able to provide.', max_length=50, verbose_name='type of work')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_type',
        ),
        migrations.AddField(
            model_name='user',
            name='work_type',
            field=models.ManyToManyField(blank=True, to='directory.worktype'),
        ),
    ]
