# Generated by Django 4.1.4 on 2022-12-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_worktype_remove_user_work_type_user_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_type',
        ),
        migrations.AddField(
            model_name='user',
            name='type_of_work',
            field=models.ManyToManyField(blank=True, help_text='eg: Prototype, Production, Made to Order, etc.', to='directory.worktype'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='work_type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
