# Generated by Django 4.1.4 on 2022-12-20 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0006_userinfo_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkidUserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='state or province')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='zip or postal code')),
                ('country', models.CharField(blank=True, max_length=56)),
                ('materials', models.ManyToManyField(blank=True, to='directory.material')),
                ('skills', models.ManyToManyField(blank=True, to='directory.skill')),
                ('type_of_work', models.ManyToManyField(blank=True, help_text='eg: Prototype, Production, Made to Order, etc.', to='directory.worktype')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
