# Generated by Django 4.1.4 on 2022-12-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_skiduserdetail_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiduserdetail',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=140, null=True, unique=True),
        ),
    ]
