# Generated by Django 4.1.4 on 2022-12-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_skiduserdetail_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiduserdetail',
            name='display_name',
            field=models.CharField(default='johnsmith', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
