# Generated by Django 4.1.4 on 2022-12-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_skiduserdetail_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skiduserdetail',
            name='slug',
        ),
    ]
