# Generated by Django 4.1.4 on 2022-12-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_remove_skiduserdetail_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skiduserdetail',
            name='display_name',
        ),
        migrations.AddField(
            model_name='skiduserdetail',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='skiduserdetail',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
