# Generated by Django 4.1.4 on 2022-12-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_remove_skiduserdetail_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiduserdetail',
            name='slug',
            field=models.SlugField(default='johnsmith', unique=True),
            preserve_default=False,
        ),
    ]
