# Generated by Django 4.1.4 on 2023-01-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_alter_skiduserdetail_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skiduserdetail',
            name='slug',
        ),
    ]
