# Generated by Django 4.1.4 on 2023-01-05 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0017_remove_skiduserdetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiduserdetail',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, verbose_name='State or Province'),
        ),
        migrations.AlterField(
            model_name='skiduserdetail',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zip or Postal Code'),
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, default='', max_length=140, null=True, unique=True)),
                ('text', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Draft'), ('p', 'Publish')], default='d', max_length=1)),
                ('materials', models.ManyToManyField(blank=True, help_text='Type of materials needed for this Idea.', related_name='idea', to='directory.material')),
                ('skills', models.ManyToManyField(blank=True, help_text='Type of skills needed for this Idea.', related_name='idea', to='directory.skill')),
                ('type_of_work', models.ManyToManyField(blank=True, help_text='How many do you need made? eg: one = prototype, many = production, etc.', related_name='idea', to='directory.worktype')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
