# Generated by Django 4.1.4 on 2023-01-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0018_alter_skiduserdetail_state_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiduserdetail',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
