# Generated by Django 4.1.4 on 2023-01-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_skiduserdetail_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skiduserdetail',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='skiduserdetail',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='skiduserdetail',
            name='type_of_work',
        ),
        migrations.RemoveField(
            model_name='skiduserdetail',
            name='username',
        ),
        migrations.DeleteModel(
            name='Idea',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='SkidUserDetail',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='WorkType',
        ),
    ]
